version: 0.2

env:
  variables:
    APP_ENV: "development"

phases:
  install:
    commands:
      - echo Installing dependency...
      - npx install -g next
      - npx install -g typescript
      - npx install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npx run build
artifacts:
  files:
    - "**/*"
  discard-paths: yes